export const LANG = {
  id: {
    langLabel:  'English',
    langNext:   'en',
    langFlag:   'EN',
    hint:       'Klik amplop untuk membuka kartu ucapan',
    ctaText:    'Buka Kartu Ucapan',
    arabic:     'بِسْمِ اللهِ الرَّحْمٰنِ الرَّحِيْمِ',
    arabicSub:  'Bismillāhir-Raḥmānir-Raḥīm',
    line1:      'Minal Aaidiin',
    line2:      'Wal Faaiziin',
    sub:        'Mohon Maaf Lahir dan Batin',
    body:       'Semoga di hari yang penuh kemenangan ini, Allah SWT menerima seluruh amal ibadah kita dan mengampuni segala khilaf. Kita kembali kepada fitrah yang suci.',
    dua:        'Taqabbalallahu Minna Wa Minkum',
    year:       '1 Syawal 1447 H',
    wishes: [
      'Maaf Lahir & Batin',
      'Berkah & Barokah',
      'Kembali Suci',
      'Damai Sejahtera',
      'Amal Diterima',
      'Penuh Kebaikan',
    ],
    senderFrom: 'Ucapan dari',
    senderSub:  'Majelis Permusyawaratan Kelas & Organisasi Siswa Intra Sekolah',
    btnShare:   'Bagikan Ucapan',
    btnSave:    'Simpan Kartu',
    toast:      'Link berhasil disalin!',
    tapToOpen:  '↑ Klik kartu untuk membuka',
    footer:     'Kartu Ucapan Digital',
  },
  en: {
    langLabel:  'Indonesia',
    langNext:   'id',
    langFlag:   'ID',
    hint:       'Click the envelope to open your greeting card',
    ctaText:    'Open Greeting Card',
    arabic:     'بِسْمِ اللهِ الرَّحْمٰنِ الرَّحِيْمِ',
    arabicSub:  'In the name of Allah, the Most Gracious, the Most Merciful',
    line1:      'Happy Eid',
    line2:      'Mubarak',
    sub:        'May this Eid bring joy & endless blessings',
    body:       'Wishing you and your beloved family a joyful Eid celebration, filled with peace, love, gratitude, and the mercy of Allah SWT.',
    dua:        'Taqabbalallahu Minna Wa Minkum',
    year:       '1 Syawal 1447 H',
    wishes: [
      'Forgiveness & Grace',
      'Blessings Abound',
      'Pure & Renewed',
      'Peace & Happiness',
      'Deeds Accepted',
      'Full of Goodness',
    ],
    senderFrom: 'Greetings from',
    senderSub:  'Student Council (MPK) & Student Organization (OSIS)',
    btnShare:   'Share Greeting',
    btnSave:    'Save Card',
    toast:      'Link copied to clipboard!',
    tapToOpen:  '↑ Tap card to open',
    footer:     'Digital Greeting Card',
  },
}
